----- CREACION DE STORE PROCEDURE-----

/* A CONTINUACION SEGUIDO DE ESTE COMENTARIO PROCEDI A CREAR UN STORE PROCEDURE `SP_INSERTAR_DATOS_PACIENTES` QUE ME PERMITE INSERTAR DATOS 
A LA TABLA PACIENTE. 
PARA ELLO DEFINI LOS PARAMETROS NECESARIOS, PARA EL INGRESO EN CADA CAMPO DE LA TABLA JUNTO CON SU TIPO DE DATO.
LUEGO DE LA CREACION DEL SP PROCEDI A INVOCAR EL MISMO CON EL COMANDO CALL Y A REALIZAR UNA PRUEBA DE INSERCION */

DROP procedure IF EXISTS `SP_INSERTAR_DATOS_PACIENTES`;
DELIMITER $$
CREATE PROCEDURE `SP_INSERTAR_DATOS_PACIENTES` (IN P_ID_PACIENTE INT,
                                                IN P_NOMBRE_PACIENTE VARCHAR(50),
                                                IN P_APELLIDO_PACIENTE VARCHAR(50),
                                                IN P_CEDULA_PACIENTE VARCHAR(50),
												IN P_FECHA_NACIMIENTO DATE,
                                                IN P_TELEFONO_PACIENTE VARCHAR(20),
                                                IN P_DIRECCION_PACIENTE VARCHAR(100),
												IN P_EMAIL_PACIENTE VARCHAR(100))
                                                                                                
BEGIN
INSERT INTO HOSPITAL_BAUTISTA.PACIENTE
VALUES (P_ID_PACIENTE, P_NOMBRE_PACIENTE, P_APELLIDO_PACIENTE, P_CEDULA_PACIENTE, P_FECHA_NACIMIENTO,
        P_TELEFONO_PACIENTE, P_DIRECCION_PACIENTE, P_EMAIL_PACIENTE);
END$$

DELIMITER ;

CALL `SP_INSERTAR_DATOS_PACIENTES` (17, 'ANITA', 'RAMIREZ', '27209173-0', '1960-07-25', '947775208', 'SANTIAGO, REGION METROPOLITANA', 'ANITA.RAMIREZD@GMAIL.COM');
----- INGRESÉ LOS DATOS DE ANITA Y LUEGO REALICÉ UNA CONSULTA PARA VERIFICAR QUE HABÍA REALIZADO CORRECTAMENTE EL INGRESO----

SELECT * FROM `PACIENTE`;

----- EL SEGUNDO PROCEDIMIENTO ME PERMITE ORDENAR LOS CAMPOS DE LA TABLA PACIENTE DE FORMA ASCENDENTE O DESCENDENTE----

DROP procedure IF EXISTS `SP_ORDENAR_PACIENTES`;
DELIMITER $$
CREATE PROCEDURE  `SP_ORDENAR_PACIENTES` (IN P_NOMBRE_COLUMNA VARCHAR(50), IN P_ORDEN VARCHAR(50))
BEGIN
SET @sqlQuery = CONCAT('SELECT * FROM PACIENTE ORDER BY ', P_NOMBRE_COLUMNA,' ', P_ORDEN);
    PREPARE stmt FROM @sqlQuery;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;

CALL SP_ORDENAR_PACIENTES ('APELLIDO_PACIENTE', 'ASC');
CALL SP_ORDENAR_PACIENTES ('APELLIDO_PACIENTE', 'DESC');
