DROP SCHEMA IF EXISTS HOSPITAL_BAUTISTA;
CREATE SCHEMA HOSPITAL_BAUTISTA;
USE HOSPITAL_BAUTISTA;

DROP TABLE IF EXISTS `PACIENTE`;
CREATE TABLE IF NOT EXISTS `PACIENTE`(
`ID_PACIENTE` INT NOT NULL PRIMARY KEY,
`NOMBRE_PACIENTE` VARCHAR(50),
`APELLIDO_PACIENTE` VARCHAR(50),
`CEDULA_PACIENTE` CHAR(15),
`FECHA_NACIMIENTO` DATE,
`TELEFONO_PACIENTE` VARCHAR(20),
`DIRECCION_PACIENTE` VARCHAR(100),
`EMAIL_PACIENTE` VARCHAR(100))
COMMENT='TABLA CON INFORMACION DEL PACIENTE'; 

DROP TABLE IF EXISTS `MEDICO`;
CREATE TABLE `MEDICO`(
`ID_MEDICO` INT NOT NULL PRIMARY KEY,
`NOMBRE_MEDICO` VARCHAR(15),
`APELLIDO_MEDICO` VARCHAR(15),
`EMAIL_MEDICO` VARCHAR(100)) 
COMMENT='TABLA CON INFORMACION DEL MEDICO'; 

DROP TABLE IF EXISTS `CONSULTORIO`; 
CREATE TABLE `CONSULTORIO`(
`ID_CONSULTORIO` INT NOT NULL PRIMARY KEY,
`NUMERO_CONSULTORIO` VARCHAR(15),
`UBICACION` VARCHAR(30))
COMMENT='TABLA DE LOS CONSULTORIOS QUE TIENE EL HOSPITAL'; 

DROP TABLE IF EXISTS `FARMACIA`;
CREATE TABLE `FARMACIA`(
`ID_MEDICAMENTO` INT NOT NULL PRIMARY KEY,
`NOMBRE_MEDICAMENTO` VARCHAR(30),
`LOTE` VARCHAR(30),
`FECHA_CADUCIDAD` DATE,
`STOCK_MEDICAMENTO` INT,
`NOTAS` VARCHAR(100))
COMMENT='TABLA CON INFORMACION DE LOS MEDICAMENTOS QUE TIENE EL HOSPITAL';

DROP TABLE IF EXISTS `ESPECIALIDAD_MEDICO`;
CREATE TABLE `ESPECIALIDAD_MEDICO`(
`ID_ESPECIALIDAD` INT NOT NULL PRIMARY KEY,
`NOMBRE_ESPECIALIDAD` VARCHAR(100),
`ID_MEDICO` INT,
CONSTRAINT `FK_ESPECIALIDAD_MEDICO_MEDICO` FOREIGN KEY (ID_MEDICO) REFERENCES `MEDICO` (ID_MEDICO))
COMMENT='TABLA CON INFORMACION DE LA ESPECIALIDAD DE LOS MEDICOS DEL HOSPITAL';

DROP TABLE IF EXISTS `CONSULTORIO_MEDICO`;
CREATE TABLE `CONSULTORIO_MEDICO`(
`CONSULTORIO_MEDICO_ID` INT NOT NULL PRIMARY KEY,
`ID_CONSULTORIO` INT,
`ID_MEDICO` INT,
CONSTRAINT `FK_CONSULTORIO_MEDICO_MEDICO` FOREIGN KEY (ID_MEDICO) REFERENCES `MEDICO` (ID_MEDICO),
CONSTRAINT `FK_CONSULTORIO_MEDICO_CONSULTORIO` FOREIGN KEY (ID_CONSULTORIO) REFERENCES `CONSULTORIO` (ID_CONSULTORIO))
COMMENT='TABLA CON INFORMACION QUE RELACIONA AL MEDICO CON EL CONSULTORIO EN DONDE ATIENDE';


DROP TABLE IF EXISTS `CITA_PACIENTE_MEDICO`;
CREATE TABLE `CITA_PACIENTE_MEDICO`(
`ID_CITA` INT NOT NULL PRIMARY KEY,
`FECHA_CITA` DATETIME,
`ESTADO_CITA` VARCHAR(50),
`ID_PACIENTE` INT,
`ID_MEDICO` INT,
CONSTRAINT `FK_CITA_PACIENTE` FOREIGN KEY (ID_PACIENTE) REFERENCES `PACIENTE` (ID_PACIENTE),
CONSTRAINT `FK_CITA_MEDICO` FOREIGN KEY (ID_MEDICO) REFERENCES `MEDICO` (ID_MEDICO))
COMMENT='TABLA DE CITAS MEDICA';

DROP TABLE IF EXISTS `HISTORIA_PACIENTE`;
CREATE TABLE `HISTORIA_PACIENTE`(
`ID_HISTORIA` INT NOT NULL PRIMARY KEY,
`HORA_ENTRADA` TIME,
`HORA_SALIDA` TIME,
`DIAGNOSTICO` VARCHAR(500),
`OBSERVACIONES` VARCHAR(1000),
`ID_PACIENTE` INT,
`ID_MEDICO` INT,
CONSTRAINT `FK_HISTORIA_PACIENTE_PACIENTE` FOREIGN KEY (ID_PACIENTE) REFERENCES `PACIENTE` (ID_PACIENTE),
CONSTRAINT `FK_HISTORIA_PACIENTE_MEDICO` FOREIGN KEY (ID_MEDICO) REFERENCES `MEDICO` (ID_MEDICO))
COMMENT='TABLA DE HISTORIA MEDICA';

DROP TABLE IF EXISTS `PRESCRIPCIONES`;
CREATE TABLE `PRESCRIPCIONES`(
`ID_PRESCRIPCION` INT NOT NULL PRIMARY KEY,
`ID_MEDICAMENTO` INT,
`ID_PACIENTE` INT,
`ID_MEDICO` INT,
`ID_HISTORIA` INT,
CONSTRAINT `FK_PRESCRIPCION_FARMACIA` FOREIGN KEY (ID_MEDICAMENTO) REFERENCES `FARMACIA` (ID_MEDICAMENTO),
CONSTRAINT `FK_PRESCRIPCION_PACIENTE` FOREIGN KEY (ID_PACIENTE) REFERENCES `PACIENTE` (ID_PACIENTE),
CONSTRAINT `FK_PRESCRIPCION_MEDICO` FOREIGN KEY (ID_MEDICO) REFERENCES `MEDICO` (ID_MEDICO))
COMMENT='TABLA QUE RELACIONA LAS TABLAS FARMACIA, PACIENTE, MEDICO';

DROP TABLE IF EXISTS `FACTURA`;
CREATE TABLE `FACTURA`(
`ID_FACTURA` INT NOT NULL PRIMARY KEY,
`NUMERO_FACTURA` VARCHAR(30),
`FECHA_FACTURA` DATE,
`MONTO_PAGADO_CLP` VARCHAR(100),
`METODO_PAGO` VARCHAR(30),
`ID_PACIENTE` INT NOT NULL,
`ID_ESPECIALIDAD` INT,
CONSTRAINT `FK_FACTURA_PACIENTE` FOREIGN KEY (ID_PACIENTE) REFERENCES `PACIENTE` (ID_PACIENTE),
CONSTRAINT `FK_FACTURA_ESPECIALIDAD` FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES `ESPECIALIDAD_MEDICO` (ID_ESPECIALIDAD))
COMMENT= "TABLA DE FACTURA CON EL PAGO DE LOS DATOS DE PAGO DE LA CONSULTA";
